var municipios= 	[{"antioquia","Antioquia"},
					{"arauca","Arauca"},
					{"archipielagodesanandres","Archipiélago de San Andrés"},
					{"atlantico","Atlántico"},
					{"bolivar","Bolívar"},
					{"boyaca","Boyacá"},
					{"caldas","Caldas"},
					{"caqueta","Caquetá"},
					{"casanare","Casanare"},
					{"cauca","Cauca"},
					{"cesar","Cesar"},
					{"choco","Chocó"},
					{"cordoba","Córdoba"},
					{"cundinamarca","Cundinamarca"},
					{"guaviare","Guaviare"},
					{"huila","Huila"},
					{"laguajira","La Guajira"},
					{"magdalena","Magdalena"},
					{"meta","Meta"},
					{"narino","Nariño"},
					{"nortedesantader","Norte de Santander"},
					{"putumayo","Putumayo"},
					{"quindio","Quindio"},
					{"risaralda","Risaralda"},
					{"santander","Santander"},
					{"sucre","Sucre"},
					{"tolima","Tolima"},
					{"valledelcauca","Valle del Cauca"},
					{"vaupes","Vaupés"},
					{"vichada","Vichada"}
					];
var cuninodaloes= [{"palmira","Palmira"},
					{"sangil","San Gil"},
					{"ibague","Ibagué"},
					{"fusagasuga","Fusagasugá}",
					{"cartago","Cartago"},
					{"guadalajaradebuga","Guadalajara de Buga"},
					{"valledupar","Valledupar"},
					{"neiva","Neiva"},
					{"pamplona","Pamplona"},
					{"sanandres","San Andrés"},
					{"popayan","Popayán"},
					{"santamartha","Santa Marta"},
					{"malaga","Málaga"},
					{"monteria""Montería"},
					{"rarrancabermeja","Barrancabermeja"},
					{"sincelejo","Sincelejo"},
					{"honda","Honda"},
					{"apartado","Apartadó"},
					{"ocana","Ocaña"},
					{"yopal","Yopal"},
					{"turbo","Turbo"},
					{"florencia","Florencia"},
					{"arauca","Arauca"},
					{"buenaventura","Buenaventura"},
					{"caucasia","Caucasia"},
					{"cienaga","Ciénaga"},
					{"maicao","Maicao"},
					{"quibdo","Quibdó"},
					{"ipiales","Ipiales"},
					{"riohacha","Riohacha"},
					{"leticia","Leticia"},
					{"mocoa","Mocoa"},
					{"puertocarreno","Puerto Carreño"},
					{"inirida","Inírida"},
					{"mitu","Mitú"},
					{"sanjosedelguaviare","San José del Guaviare"},
					{"puertoasis","Puerto Asís"},
					{"sanandresdetumaco","San Andres de Tumaco"}
					];
var aglomeraciones = [{"A-Bogota, D.C.","Aglomeración de Bogotá, D.C."},
						{"A-Medellin","Aglomeración de Medellín"},
						{"A-Bucaramanga","Aglomeración de Bucaramanga"},
						{"A-Cali","Aglomeración de Cali"},
						{"A-Tunja","Aglomeración de Tunja"},
						{"A-Manizales","Aglomeración de Manizales"},
						{"A-Barranquilla","Aglomeración de Barranquilla"},
						{"A-Pereira","Aglomeración de Pereira"},
						{"A-Duitama","Aglomeración de Duitama"},
						{"A-Rionegro","Aglomeración de Rionegro"},
						{"A-Pasto""Aglomeración de Pasto"},
						{"A-Sogamoso","Aglomeración de Sogamoso"},
						{"A-Cartagena","Aglomeración de Cartagena"},
						{"A-Armenia","Aglomeración de Armenia"},
						{"A-Girardot","Aglomeración de Girardot"},
						{"A-Villavicencio","Aglomeración de Villavicencio"},	
						{"A-Cucuta","Aglomeración de Cúcuta"},
						{"A-Tulua","Aglomeración de Tuluá"}]
						

